### ISSUE TITLE
Factorise code in github workflows

### ISSUE THREAD

**Issue by fabiencelier** [atoti/jdk4py#23]
All the jobs starts with the same set of steps to setup every thing:

```yaml
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: "x64"

      - name: Set Java version
        run: python scripts/set_versions.py

      - uses: joschi/setup-jdk@v2 # We must use to the official action once https://github.com/actions/setup-java/pull/97 is closed
        with:
          java-version: ${{ env.MAJOR_JAVA_VERSION }}
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64

      # Install Poetry
      - if: matrix.os == 'windows-latest'
        name: Install poetry [Windows]
        run: pip install poetry
      - if: matrix.os != 'windows-latest'
        name: Install poetry [Ubuntu/macOS]
        run: pip3 install poetry

      - name: Install python dependencies
        run: poetry install

      - name: Build JDK
        run: poetry run python scripts/build_jdk.py
```

We should factorize it to avoid changing the same thing multiple times.

I have tried putting them into a [composite action](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-composite-run-steps-action) but it doesn't support the `uses` steps
